# -*- coding: utf-8 -*-
"""data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z9Tol9d6EfHnfbxIQyVZQI_Lc7P1MSCT
"""

import pandas as pd
import random
from datetime import datetime, timedelta

random.seed(42)

rows = 1200

regions = ["North", "South", "East", "West"]
cities = ["Medellín", "Bogotá", "Cali", "Barranquilla", "Bucaramanga"]
channels = ["Online", "Store"]
categories = ["Footwear", "Clothing", "Accessories"]
products = {
    "Footwear": ["Running Shoes", "Sneakers", "Sandals"],
    "Clothing": ["T-Shirts", "Hoodies", "Pants"],
    "Accessories": ["Backpacks", "Caps", "Socks"]
}
sales_reps = ["Ana", "Carlos", "Luis", "María", "Sofía"]
payments = ["Credit Card", "Debit Card", "Cash", "Transfer"]

start_date = datetime(2024, 1, 1)

data = []

for i in range(rows):
    category = random.choice(categories)
    product = random.choice(products[category])
    quantity = random.randint(1, 5)
    unit_price = random.randint(20, 150)
    total_sales = quantity * unit_price

    data.append({
        "Order_ID": 10000 + i,
        "Order_Date": start_date + timedelta(days=random.randint(0, 364)),
        "Region": random.choice(regions),
        "City": random.choice(cities),
        "Sales_Channel": random.choice(channels),
        "Product_Category": category,
        "Product_Name": product,
        "Quantity": quantity,
        "Unit_Price": unit_price,
        "Total_Sales": total_sales,
        "Sales_Rep": random.choice(sales_reps),
        "Payment_Method": random.choice(payments)
    })

df = pd.DataFrame(data)
df.to_csv("sales_data.csv", index=False)

df.head()

df.to_excel("sales_data.xlsx", index=False)
print("DataFrame guardado como sales_data.xlsx")

from google.colab import files

files.download('sales_data.xlsx')

"""Al ejecutar el código anterior, deberías ver que el archivo `sales_data.xlsx` se descarga en tu navegador. Si no ves el archivo inmediatamente, revisa tu carpeta de descargas predeterminada."""